namespace ns14
{
	// Token: 0x020001D3 RID: 467
	internal sealed partial class GagAMatic : global::ns14.Form0
	{
		// Token: 0x06001538 RID: 5432 RVA: 0x00005997 File Offset: 0x00003B97
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.icontainer_0 != null)
			{
				this.icontainer_0.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06001539 RID: 5433 RVA: 0x0002D8D0 File Offset: 0x0002BAD0
		private void InitializeComponent()
		{
			this.icontainer_0 = new global::System.ComponentModel.Container();
			global::ns24.Control4.Class311 @class = new global::ns24.Control4.Class311();
			global::ns25.Class324 class2 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class3 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class4 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class5 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class6 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class7 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class8 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class9 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class10 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class11 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class12 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class13 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class14 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class15 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class16 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class17 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class18 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class19 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class20 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class21 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class22 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class23 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class24 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class25 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class26 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class27 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class28 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class29 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class30 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class31 = new global::ns24.Control4.Class311();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ns14.GagAMatic));
			global::ns24.Control4.Class311 class32 = new global::ns24.Control4.Class311();
			global::ns24.Control4.Class311 class33 = new global::ns24.Control4.Class311();
			global::ns24.Control4.Class311 class34 = new global::ns24.Control4.Class311();
			global::ns25.Class324 class35 = new global::ns25.Class324();
			global::ns24.Control4.Class311 class36 = new global::ns24.Control4.Class311();
			global::ns24.Control4.Class311 class37 = new global::ns24.Control4.Class311();
			global::ns24.Control4.Class311 class38 = new global::ns24.Control4.Class311();
			global::ns24.Control4.Class311 class39 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class40 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class41 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class42 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class43 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class44 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class45 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class46 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class47 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class48 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class49 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class50 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class51 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class52 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class53 = new global::ns24.Control4.Class311();
			global::ns25.Class323 overlay = new global::ns25.Class323();
			global::ns24.Control4.Class311 class54 = new global::ns24.Control4.Class311();
			global::ns25.Class323 overlay2 = new global::ns25.Class323();
			global::ns24.Control4.Class311 class55 = new global::ns24.Control4.Class311();
			global::ns25.Class323 overlay3 = new global::ns25.Class323();
			global::ns24.Control4.Class311 class56 = new global::ns24.Control4.Class311();
			global::ns25.Class323 overlay4 = new global::ns25.Class323();
			global::ns24.Control4.Class311 class57 = new global::ns24.Control4.Class311();
			global::ns25.Class323 overlay5 = new global::ns25.Class323();
			global::ns24.Control4.Class311 class58 = new global::ns24.Control4.Class311();
			global::ns25.Class323 overlay6 = new global::ns25.Class323();
			global::ns24.Control4.Class311 class59 = new global::ns24.Control4.Class311();
			global::ns25.Class323 overlay7 = new global::ns25.Class323();
			global::ns24.Control4.Class311 class60 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class61 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class62 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class63 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class64 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class65 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class66 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class67 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class68 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class69 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class70 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class71 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class72 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class73 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class74 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class75 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class76 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class77 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class78 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class79 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class80 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class81 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class82 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class83 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class84 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class85 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class86 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class87 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class88 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class89 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class90 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class91 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class92 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class93 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class94 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class95 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class96 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class97 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class98 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class99 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class100 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class101 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class102 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class103 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class104 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class105 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class106 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class107 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class108 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class109 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class110 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class111 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class112 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class113 = new global::ns25.Class325();
			global::ns24.Control4.Class311 class114 = new global::ns24.Control4.Class311();
			global::ns25.Class325 class115 = new global::ns25.Class325();
			this.Lured = new global::System.Windows.Forms.CheckBox();
			this.ToonUpTitle = new global::System.Windows.Forms.Label();
			this.label2 = new global::System.Windows.Forms.Label();
			this.label3 = new global::System.Windows.Forms.Label();
			this.label4 = new global::System.Windows.Forms.Label();
			this.label5 = new global::System.Windows.Forms.Label();
			this.label6 = new global::System.Windows.Forms.Label();
			this.label7 = new global::System.Windows.Forms.Label();
			this.label8 = new global::System.Windows.Forms.Label();
			this.label9 = new global::System.Windows.Forms.Label();
			this.label10 = new global::System.Windows.Forms.Label();
			this.label11 = new global::System.Windows.Forms.Label();
			this.label12 = new global::System.Windows.Forms.Label();
			this.label13 = new global::System.Windows.Forms.Label();
			this.label14 = new global::System.Windows.Forms.Label();
			this.btnClear = new global::System.Windows.Forms.Button();
			this.label15 = new global::System.Windows.Forms.Label();
			this.ClearButtonPanel = new global::System.Windows.Forms.Panel();
			this.MaxCogTitle = new global::System.Windows.Forms.Label();
			this.MaxCog = new global::System.Windows.Forms.Label();
			this.HitPoints = new global::System.Windows.Forms.Label();
			this.KeepOnTop = new global::System.Windows.Forms.CheckBox();
			this.ShowToolTips = new global::System.Windows.Forms.CheckBox();
			this.toolTip_0 = new global::System.Windows.Forms.ToolTip(this.icontainer_0);
			this.MaxMessage = new global::ns15.TextFader();
			this.SosBoard = new global::ns24.Control4();
			this.GagBoard = new global::ns24.Control4();
			this.HowToOpenHelpLabel = new global::System.Windows.Forms.Label();
			this.ClearButtonPanel.SuspendLayout();
			base.SuspendLayout();
			this.Lured.BackColor = global::System.Drawing.Color.FromArgb(109, 205, 117);
			this.Lured.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.Lured.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Lured.Location = new global::System.Drawing.Point(19, 158);
			this.Lured.Name = "Lured";
			this.Lured.Size = new global::System.Drawing.Size(82, 61);
			this.Lured.TabIndex = 1;
			this.Lured.Text = "Check if Cogs are already lured.";
			this.Lured.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.toolTip_0.SetToolTip(this.Lured, "If Cogs are already lured, check here.");
			this.Lured.UseVisualStyleBackColor = false;
			this.Lured.CheckedChanged += new global::System.EventHandler(this.Lured_CheckedChanged);
			this.ToonUpTitle.AutoSize = true;
			this.ToonUpTitle.BackColor = global::System.Drawing.Color.FromArgb(194, 136, 237);
			this.ToonUpTitle.Location = new global::System.Drawing.Point(129, 128);
			this.ToonUpTitle.Name = "ToonUpTitle";
			this.ToonUpTitle.Size = new global::System.Drawing.Size(56, 13);
			this.ToonUpTitle.TabIndex = 2;
			this.ToonUpTitle.Text = "TOON-UP";
			this.label2.BackColor = global::System.Drawing.Color.FromArgb(194, 136, 237);
			this.label2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.label2.Font = new global::System.Drawing.Font("Segoe UI", 6f);
			this.label2.Location = new global::System.Drawing.Point(129, 141);
			this.label2.Name = "label2";
			this.label2.Size = new global::System.Drawing.Size(56, 13);
			this.label2.TabIndex = 2;
			this.label2.Text = "9999 / 9999";
			this.label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.label3.AutoSize = true;
			this.label3.BackColor = global::System.Drawing.Color.FromArgb(229, 235, 87);
			this.label3.Location = new global::System.Drawing.Point(129, 158);
			this.label3.Name = "label3";
			this.label3.Size = new global::System.Drawing.Size(36, 13);
			this.label3.TabIndex = 2;
			this.label3.Text = "TRAP";
			this.label4.BackColor = global::System.Drawing.Color.FromArgb(229, 235, 87);
			this.label4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.label4.Font = new global::System.Drawing.Font("Segoe UI", 6f);
			this.label4.Location = new global::System.Drawing.Point(129, 171);
			this.label4.Name = "label4";
			this.label4.Size = new global::System.Drawing.Size(56, 13);
			this.label4.TabIndex = 2;
			this.label4.Text = "9999 / 9999";
			this.label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.label5.AutoSize = true;
			this.label5.BackColor = global::System.Drawing.Color.FromArgb(74, 175, 71);
			this.label5.Location = new global::System.Drawing.Point(129, 188);
			this.label5.Name = "label5";
			this.label5.Size = new global::System.Drawing.Size(36, 13);
			this.label5.TabIndex = 2;
			this.label5.Text = "LURE";
			this.label6.BackColor = global::System.Drawing.Color.FromArgb(74, 175, 71);
			this.label6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.label6.Font = new global::System.Drawing.Font("Segoe UI", 6f);
			this.label6.Location = new global::System.Drawing.Point(129, 201);
			this.label6.Name = "label6";
			this.label6.Size = new global::System.Drawing.Size(56, 13);
			this.label6.TabIndex = 2;
			this.label6.Text = "9999 / 9999";
			this.label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.label7.AutoSize = true;
			this.label7.BackColor = global::System.Drawing.Color.FromArgb(85, 100, 219);
			this.label7.Location = new global::System.Drawing.Point(129, 218);
			this.label7.Name = "label7";
			this.label7.Size = new global::System.Drawing.Size(46, 13);
			this.label7.TabIndex = 2;
			this.label7.Text = "SOUND";
			this.label8.BackColor = global::System.Drawing.Color.FromArgb(85, 100, 219);
			this.label8.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.label8.Font = new global::System.Drawing.Font("Segoe UI", 6f);
			this.label8.Location = new global::System.Drawing.Point(129, 231);
			this.label8.Name = "label8";
			this.label8.Size = new global::System.Drawing.Size(56, 13);
			this.label8.TabIndex = 2;
			this.label8.Text = "9999 / 9999";
			this.label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.label9.AutoSize = true;
			this.label9.BackColor = global::System.Drawing.Color.FromArgb(235, 135, 60);
			this.label9.Location = new global::System.Drawing.Point(129, 248);
			this.label9.Name = "label9";
			this.label9.Size = new global::System.Drawing.Size(49, 13);
			this.label9.TabIndex = 2;
			this.label9.Text = "THROW";
			this.label10.BackColor = global::System.Drawing.Color.FromArgb(235, 135, 60);
			this.label10.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.label10.Font = new global::System.Drawing.Font("Segoe UI", 6f);
			this.label10.Location = new global::System.Drawing.Point(129, 261);
			this.label10.Name = "label10";
			this.label10.Size = new global::System.Drawing.Size(56, 13);
			this.label10.TabIndex = 2;
			this.label10.Text = "9999 / 9999";
			this.label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.label11.AutoSize = true;
			this.label11.BackColor = global::System.Drawing.Color.FromArgb(234, 59, 184);
			this.label11.Location = new global::System.Drawing.Point(129, 278);
			this.label11.Name = "label11";
			this.label11.Size = new global::System.Drawing.Size(48, 13);
			this.label11.TabIndex = 2;
			this.label11.Text = "SQUIRT";
			this.label12.BackColor = global::System.Drawing.Color.FromArgb(234, 59, 184);
			this.label12.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.label12.Font = new global::System.Drawing.Font("Segoe UI", 6f);
			this.label12.Location = new global::System.Drawing.Point(129, 291);
			this.label12.Name = "label12";
			this.label12.Size = new global::System.Drawing.Size(56, 13);
			this.label12.TabIndex = 2;
			this.label12.Text = "9999 / 9999";
			this.label12.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.label13.AutoSize = true;
			this.label13.BackColor = global::System.Drawing.Color.FromArgb(62, 224, 235);
			this.label13.Location = new global::System.Drawing.Point(129, 308);
			this.label13.Name = "label13";
			this.label13.Size = new global::System.Drawing.Size(38, 13);
			this.label13.TabIndex = 2;
			this.label13.Text = "DROP";
			this.label14.BackColor = global::System.Drawing.Color.FromArgb(62, 224, 235);
			this.label14.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.label14.Font = new global::System.Drawing.Font("Segoe UI", 6f);
			this.label14.Location = new global::System.Drawing.Point(129, 321);
			this.label14.Name = "label14";
			this.label14.Size = new global::System.Drawing.Size(56, 13);
			this.label14.TabIndex = 2;
			this.label14.Text = "9999 / 9999";
			this.label14.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.btnClear.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnClear.Location = new global::System.Drawing.Point(0, 0);
			this.btnClear.Name = "btnClear";
			this.btnClear.Size = new global::System.Drawing.Size(75, 44);
			this.btnClear.TabIndex = 5;
			this.btnClear.Text = "Clear";
			this.toolTip_0.SetToolTip(this.btnClear, "Clears all Gag and SOS Card selections.");
			this.btnClear.UseVisualStyleBackColor = true;
			this.btnClear.Click += new global::System.EventHandler(this.btnClear_Click);
			this.label15.AutoSize = true;
			this.label15.BackColor = global::System.Drawing.Color.FromArgb(109, 205, 117);
			this.label15.Location = new global::System.Drawing.Point(192, 99);
			this.label15.Name = "label15";
			this.label15.Size = new global::System.Drawing.Size(300, 13);
			this.label15.TabIndex = 7;
			this.label15.Text = "Left Click for Normal Damage, Right Click for Organic Damage";
			this.ClearButtonPanel.BackColor = global::System.Drawing.Color.FromArgb(109, 205, 117);
			this.ClearButtonPanel.Controls.Add(this.btnClear);
			this.ClearButtonPanel.Location = new global::System.Drawing.Point(116, 372);
			this.ClearButtonPanel.Name = "ClearButtonPanel";
			this.ClearButtonPanel.Size = new global::System.Drawing.Size(75, 44);
			this.ClearButtonPanel.TabIndex = 8;
			this.MaxCogTitle.AutoSize = true;
			this.MaxCogTitle.BackColor = global::System.Drawing.Color.FromArgb(105, 245, 255);
			this.MaxCogTitle.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.MaxCogTitle.Location = new global::System.Drawing.Point(587, 154);
			this.MaxCogTitle.Name = "MaxCogTitle";
			this.MaxCogTitle.Size = new global::System.Drawing.Size(71, 20);
			this.MaxCogTitle.TabIndex = 9;
			this.MaxCogTitle.Text = "Max Cog";
			this.MaxCog.BackColor = global::System.Drawing.Color.FromArgb(105, 245, 255);
			this.MaxCog.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.MaxCog.Location = new global::System.Drawing.Point(586, 185);
			this.MaxCog.Name = "MaxCog";
			this.MaxCog.Size = new global::System.Drawing.Size(73, 56);
			this.MaxCog.TabIndex = 9;
			this.MaxCog.Text = "Level 0";
			this.MaxCog.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.toolTip_0.SetToolTip(this.MaxCog, "The highest level of Cog the combined total damage from all selected Gags and SOS Cards can defeat.");
			this.HitPoints.BackColor = global::System.Drawing.Color.FromArgb(253, 182, 94);
			this.HitPoints.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.HitPoints.Location = new global::System.Drawing.Point(582, 292);
			this.HitPoints.Name = "HitPoints";
			this.HitPoints.Size = new global::System.Drawing.Size(80, 46);
			this.HitPoints.TabIndex = 9;
			this.HitPoints.Text = "Hit Points";
			this.HitPoints.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.toolTip_0.SetToolTip(this.HitPoints, "The total number of hit points of damage the combined selection of Gags and SOS Cards produce.");
			this.KeepOnTop.BackColor = global::System.Drawing.Color.FromArgb(109, 205, 117);
			this.KeepOnTop.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.KeepOnTop.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.KeepOnTop.Location = new global::System.Drawing.Point(19, 222);
			this.KeepOnTop.Name = "KeepOnTop";
			this.KeepOnTop.Size = new global::System.Drawing.Size(82, 73);
			this.KeepOnTop.TabIndex = 1;
			this.KeepOnTop.Text = "Check to make Gag-A-Matic stay on top.";
			this.KeepOnTop.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.toolTip_0.SetToolTip(this.KeepOnTop, "To make The Gag-A-Matic stay on top of other applications, check here.");
			this.KeepOnTop.UseVisualStyleBackColor = false;
			this.KeepOnTop.CheckedChanged += new global::System.EventHandler(this.KeepOnTop_CheckedChanged);
			this.ShowToolTips.BackColor = global::System.Drawing.Color.FromArgb(109, 205, 117);
			this.ShowToolTips.CheckAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.ShowToolTips.Checked = true;
			this.ShowToolTips.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.ShowToolTips.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6.75f);
			this.ShowToolTips.Location = new global::System.Drawing.Point(19, 298);
			this.ShowToolTips.Name = "ShowToolTips";
			this.ShowToolTips.Size = new global::System.Drawing.Size(82, 46);
			this.ShowToolTips.TabIndex = 1;
			this.ShowToolTips.Text = "Check to show tooltips.";
			this.ShowToolTips.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.toolTip_0.SetToolTip(this.ShowToolTips, "To show tooltips on Gags and SOS Cards, check here.");
			this.ShowToolTips.UseVisualStyleBackColor = false;
			this.ShowToolTips.CheckedChanged += new global::System.EventHandler(this.ShowToolTips_CheckedChanged);
			this.MaxMessage.BackColor = global::System.Drawing.Color.Transparent;
			this.MaxMessage.FadeOutAlphaRate = 5;
			this.MaxMessage.FadeOutDelay = 3000;
			this.MaxMessage.FadeOutRate = 10;
			this.MaxMessage.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold);
			this.MaxMessage.ForeColor = global::System.Drawing.Color.Black;
			this.MaxMessage.Location = new global::System.Drawing.Point(26, 452);
			this.MaxMessage.Name = "MaxMessage";
			this.MaxMessage.Size = new global::System.Drawing.Size(152, 21);
			this.MaxMessage.TabIndex = 10;
			this.MaxMessage.Text = "Maximum 4 Gags";
			this.SosBoard.BackColor = global::System.Drawing.Color.White;
			this.SosBoard.BackgroundPaint = null;
			this.SosBoard.ButtonOutline = global::System.Drawing.Color.FromArgb(200, 0, 0, 0);
			@class.AcceptRightClick = false;
			@class.Bounds = new global::System.Drawing.Rectangle(2, 2, 80, 24);
			@class.ButtonType = global::ns21.Enum32.const_1;
			@class.Enabled = true;
			@class.Name = "Clerk Will";
			class2.Damage = 50;
			class2.NormalQuantity = 0;
			@class.Overlay = class2;
			@class.Selected = false;
			@class.Text = "Clerk Will";
			class3.AcceptRightClick = false;
			class3.Bounds = new global::System.Drawing.Rectangle(86, 2, 80, 24);
			class3.ButtonType = global::ns21.Enum32.const_1;
			class3.Enabled = true;
			class3.Name = "Clerk Penny";
			class4.Damage = 70;
			class4.NormalQuantity = 0;
			class3.Overlay = class4;
			class3.Selected = false;
			class3.Text = "Clerk Penny";
			class5.AcceptRightClick = false;
			class5.Bounds = new global::System.Drawing.Rectangle(170, 2, 80, 24);
			class5.ButtonType = global::ns21.Enum32.const_1;
			class5.Enabled = true;
			class5.Name = "Clerk Clara";
			class6.Damage = 180;
			class6.NormalQuantity = 0;
			class5.Overlay = class6;
			class5.Selected = false;
			class5.Text = "Clerk Clara";
			class7.AcceptRightClick = false;
			class7.Bounds = new global::System.Drawing.Rectangle(254, 2, 80, 24);
			class7.ButtonType = global::ns21.Enum32.const_3;
			class7.Enabled = true;
			class7.Name = "Bea Sharpe";
			class8.Damage = 10;
			class8.NormalQuantity = 0;
			class7.Overlay = class8;
			class7.Selected = false;
			class7.Text = "Bea Sharpe";
			class9.AcceptRightClick = false;
			class9.Bounds = new global::System.Drawing.Rectangle(338, 2, 80, 24);
			class9.ButtonType = global::ns21.Enum32.const_3;
			class9.Enabled = true;
			class9.Name = "Otto Toon";
			class10.Damage = 20;
			class10.NormalQuantity = 0;
			class9.Overlay = class10;
			class9.Selected = false;
			class9.Text = "Otto Toon";
			class11.AcceptRightClick = false;
			class11.Bounds = new global::System.Drawing.Rectangle(2, 30, 80, 24);
			class11.ButtonType = global::ns21.Enum32.const_3;
			class11.Enabled = true;
			class11.Name = "Al Capella";
			class12.Damage = 30;
			class12.NormalQuantity = 0;
			class11.Overlay = class12;
			class11.Selected = false;
			class11.Text = "Al Capella";
			class13.AcceptRightClick = false;
			class13.Bounds = new global::System.Drawing.Rectangle(86, 30, 80, 24);
			class13.ButtonType = global::ns21.Enum32.const_3;
			class13.Enabled = true;
			class13.Name = "Barbara Seville";
			class14.Damage = 40;
			class14.NormalQuantity = 0;
			class13.Overlay = class14;
			class13.Selected = false;
			class13.Text = "Barbara\r\nSeville";
			class15.AcceptRightClick = false;
			class15.Bounds = new global::System.Drawing.Rectangle(170, 30, 80, 24);
			class15.ButtonType = global::ns21.Enum32.const_3;
			class15.Enabled = true;
			class15.Name = "Sid Sonata";
			class16.Damage = 50;
			class16.NormalQuantity = 0;
			class15.Overlay = class16;
			class15.Selected = false;
			class15.Text = "Sid Sonata";
			class17.AcceptRightClick = false;
			class17.Bounds = new global::System.Drawing.Rectangle(254, 30, 80, 24);
			class17.ButtonType = global::ns21.Enum32.const_3;
			class17.Enabled = true;
			class17.Name = "Moe Zart";
			class18.Damage = 80;
			class18.NormalQuantity = 0;
			class17.Overlay = class18;
			class17.Selected = false;
			class17.Text = "Moe Zart";
			class19.AcceptRightClick = false;
			class19.Bounds = new global::System.Drawing.Rectangle(338, 30, 80, 24);
			class19.ButtonType = global::ns21.Enum32.const_6;
			class19.Enabled = true;
			class19.Name = "Anne Ville";
			class20.Damage = 20;
			class20.NormalQuantity = 0;
			class19.Overlay = class20;
			class19.Selected = false;
			class19.Text = "Anne Ville";
			class21.AcceptRightClick = false;
			class21.Bounds = new global::System.Drawing.Rectangle(2, 58, 80, 24);
			class21.ButtonType = global::ns21.Enum32.const_6;
			class21.Enabled = true;
			class21.Name = "Bud Erfingerz";
			class22.Damage = 35;
			class22.NormalQuantity = 0;
			class21.Overlay = class22;
			class21.Selected = false;
			class21.Text = "Bud\r\nErfingerz";
			class23.AcceptRightClick = false;
			class23.Bounds = new global::System.Drawing.Rectangle(86, 58, 80, 24);
			class23.ButtonType = global::ns21.Enum32.const_6;
			class23.Enabled = true;
			class23.Name = "J.S. Bark";
			class24.Damage = 50;
			class24.NormalQuantity = 0;
			class23.Overlay = class24;
			class23.Selected = false;
			class23.Text = "J.S. Bark";
			class25.AcceptRightClick = false;
			class25.Bounds = new global::System.Drawing.Rectangle(170, 58, 80, 24);
			class25.ButtonType = global::ns21.Enum32.const_6;
			class25.Enabled = true;
			class25.Name = "Clumsy Ned";
			class26.Damage = 60;
			class26.NormalQuantity = 0;
			class25.Overlay = class26;
			class25.Selected = false;
			class25.Text = "Clumsy Ned";
			class27.AcceptRightClick = false;
			class27.Bounds = new global::System.Drawing.Rectangle(254, 58, 80, 24);
			class27.ButtonType = global::ns21.Enum32.const_6;
			class27.Enabled = true;
			class27.Name = "Franz Neckvein";
			class28.Damage = 100;
			class28.NormalQuantity = 0;
			class27.Overlay = class28;
			class27.Selected = false;
			class27.Text = "Franz\r\nNeckvein";
			class29.AcceptRightClick = false;
			class29.Bounds = new global::System.Drawing.Rectangle(338, 58, 80, 24);
			class29.ButtonType = global::ns21.Enum32.const_6;
			class29.Enabled = true;
			class29.Name = "Barnacle Bessie";
			class30.Damage = 170;
			class30.NormalQuantity = 0;
			class29.Overlay = class30;
			class29.Selected = false;
			class29.Text = "Barnacle\r\nBessie";
			this.SosBoard.Buttons.Add(@class);
			this.SosBoard.Buttons.Add(class3);
			this.SosBoard.Buttons.Add(class5);
			this.SosBoard.Buttons.Add(class7);
			this.SosBoard.Buttons.Add(class9);
			this.SosBoard.Buttons.Add(class11);
			this.SosBoard.Buttons.Add(class13);
			this.SosBoard.Buttons.Add(class15);
			this.SosBoard.Buttons.Add(class17);
			this.SosBoard.Buttons.Add(class19);
			this.SosBoard.Buttons.Add(class21);
			this.SosBoard.Buttons.Add(class23);
			this.SosBoard.Buttons.Add(class25);
			this.SosBoard.Buttons.Add(class27);
			this.SosBoard.Buttons.Add(class29);
			this.SosBoard.DisabledEndColor = global::System.Drawing.Color.FromArgb(37, 37, 37);
			this.SosBoard.DisabledStartColor = global::System.Drawing.Color.FromArgb(163, 163, 163);
			this.SosBoard.DownEndColor = global::System.Drawing.Color.FromArgb(111, 2, 14);
			this.SosBoard.DownStartColor = global::System.Drawing.Color.FromArgb(250, 102, 102);
			this.SosBoard.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Bold);
			this.SosBoard.HoverEndColor = global::System.Drawing.Color.FromArgb(157, 0, 18);
			this.SosBoard.HoverRadialCenterColor = global::System.Drawing.Color.FromArgb(200, 255, 0, 0);
			this.SosBoard.HoverRadialSurroundColor = global::System.Drawing.Color.FromArgb(0, 255, 0, 0);
			this.SosBoard.HoverStartColor = global::System.Drawing.Color.FromArgb(248, 152, 152);
			this.SosBoard.Location = new global::System.Drawing.Point(253, 392);
			this.SosBoard.Name = "SosBoard";
			this.SosBoard.NormalEndColor = global::System.Drawing.Color.FromArgb(1, 137, 224);
			this.SosBoard.NormalStartColor = global::System.Drawing.Color.FromArgb(76, 181, 248);
			this.SosBoard.SelectedEndColor = global::System.Drawing.Color.FromArgb(0, 157, 0);
			this.SosBoard.SelectedRadialCenterColor = global::System.Drawing.Color.FromArgb(200, 0, 255, 0);
			this.SosBoard.SelectedRadialSurroundColor = global::System.Drawing.Color.FromArgb(0, 0, 255, 0);
			this.SosBoard.SelectedStartColor = global::System.Drawing.Color.FromArgb(152, 248, 165);
			this.SosBoard.Size = new global::System.Drawing.Size(420, 84);
			this.SosBoard.TabIndex = 3;
			this.SosBoard.Text = "buttonBoard1";
			this.SosBoard.TextFont = new global::System.Drawing.Font("Microsoft Sans Serif", 6.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.SosBoard.ToolTipsEnabled = true;
			this.SosBoard.ButtonClicked += new global::System.EventHandler<global::ns17.EventArgs21>(this.method_3);
			this.GagBoard.BackColor = global::System.Drawing.Color.FromArgb(73, 193, 83);
			this.GagBoard.BackgroundPaint = null;
			this.GagBoard.ButtonOutline = global::System.Drawing.Color.FromArgb(200, 0, 0, 0);
			class31.AcceptRightClick = true;
			class31.Bounds = new global::System.Drawing.Rectangle(72, 2, 46, 26);
			class31.ButtonType = global::ns21.Enum32.const_0;
			class31.Enabled = false;
			class31.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton16.Icon");
			class31.Name = "Feather";
			class31.Overlay = null;
			class31.Selected = false;
			class31.Text = "";
			class32.AcceptRightClick = true;
			class32.Bounds = new global::System.Drawing.Rectangle(122, 2, 46, 26);
			class32.ButtonType = global::ns21.Enum32.const_0;
			class32.Enabled = false;
			class32.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton17.Icon");
			class32.Name = "Megaphone";
			class32.Overlay = null;
			class32.Selected = false;
			class32.Text = null;
			class33.AcceptRightClick = true;
			class33.Bounds = new global::System.Drawing.Rectangle(172, 2, 46, 26);
			class33.ButtonType = global::ns21.Enum32.const_0;
			class33.Enabled = false;
			class33.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton18.Icon");
			class33.Name = "Lipstick";
			class33.Overlay = null;
			class33.Selected = false;
			class33.Text = null;
			class34.AcceptRightClick = true;
			class34.Bounds = new global::System.Drawing.Rectangle(222, 2, 46, 26);
			class34.ButtonType = global::ns21.Enum32.const_0;
			class34.Enabled = false;
			class34.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton19.Icon");
			class34.Name = "Bamboo Cane";
			class35.Damage = 0;
			class35.NormalQuantity = 0;
			class34.Overlay = class35;
			class34.Selected = false;
			class34.Text = null;
			class36.AcceptRightClick = true;
			class36.Bounds = new global::System.Drawing.Rectangle(272, 2, 46, 26);
			class36.ButtonType = global::ns21.Enum32.const_0;
			class36.Enabled = false;
			class36.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton20.Icon");
			class36.Name = "PixieDust";
			class36.Overlay = null;
			class36.Selected = false;
			class36.Text = null;
			class37.AcceptRightClick = true;
			class37.Bounds = new global::System.Drawing.Rectangle(322, 2, 46, 26);
			class37.ButtonType = global::ns21.Enum32.const_0;
			class37.Enabled = false;
			class37.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton21.Icon");
			class37.Name = "Juggling Balls";
			class37.Overlay = null;
			class37.Selected = false;
			class37.Text = null;
			class38.AcceptRightClick = true;
			class38.Bounds = new global::System.Drawing.Rectangle(372, 2, 46, 26);
			class38.ButtonType = global::ns21.Enum32.const_0;
			class38.Enabled = false;
			class38.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton22.Icon");
			class38.Name = "High Dive";
			class38.Overlay = null;
			class38.Selected = false;
			class38.Text = null;
			class39.AcceptRightClick = true;
			class39.Bounds = new global::System.Drawing.Rectangle(72, 32, 46, 26);
			class39.ButtonType = global::ns21.Enum32.const_1;
			class39.Enabled = true;
			class39.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton23.Icon");
			class39.Name = "Banana Peel";
			class40.Damage = 12;
			class40.NormalQuantity = 0;
			class40.OrganicQuantity = 0;
			class39.Overlay = class40;
			class39.Selected = false;
			class39.Text = null;
			class41.AcceptRightClick = true;
			class41.Bounds = new global::System.Drawing.Rectangle(122, 32, 46, 26);
			class41.ButtonType = global::ns21.Enum32.const_1;
			class41.Enabled = true;
			class41.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton24.Icon");
			class41.Name = "Rake";
			class42.Damage = 20;
			class42.NormalQuantity = 0;
			class42.OrganicQuantity = 0;
			class41.Overlay = class42;
			class41.Selected = false;
			class41.Text = null;
			class43.AcceptRightClick = true;
			class43.Bounds = new global::System.Drawing.Rectangle(172, 32, 46, 26);
			class43.ButtonType = global::ns21.Enum32.const_1;
			class43.Enabled = true;
			class43.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton25.Icon");
			class43.Name = "Marbles";
			class44.Damage = 35;
			class44.NormalQuantity = 0;
			class44.OrganicQuantity = 0;
			class43.Overlay = class44;
			class43.Selected = false;
			class43.Text = null;
			class45.AcceptRightClick = true;
			class45.Bounds = new global::System.Drawing.Rectangle(222, 32, 46, 26);
			class45.ButtonType = global::ns21.Enum32.const_1;
			class45.Enabled = true;
			class45.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton26.Icon");
			class45.Name = "Quick Sand";
			class46.Damage = 50;
			class46.NormalQuantity = 0;
			class46.OrganicQuantity = 0;
			class45.Overlay = class46;
			class45.Selected = false;
			class45.Text = null;
			class47.AcceptRightClick = true;
			class47.Bounds = new global::System.Drawing.Rectangle(272, 32, 46, 26);
			class47.ButtonType = global::ns21.Enum32.const_1;
			class47.Enabled = true;
			class47.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton27.Icon");
			class47.Name = "Trap Door";
			class48.Damage = 70;
			class48.NormalQuantity = 0;
			class48.OrganicQuantity = 0;
			class47.Overlay = class48;
			class47.Selected = false;
			class47.Text = null;
			class49.AcceptRightClick = true;
			class49.Bounds = new global::System.Drawing.Rectangle(322, 32, 46, 26);
			class49.ButtonType = global::ns21.Enum32.const_1;
			class49.Enabled = true;
			class49.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton28.Icon");
			class49.Name = "TNT";
			class50.Damage = 180;
			class50.NormalQuantity = 0;
			class50.OrganicQuantity = 0;
			class49.Overlay = class50;
			class49.Selected = false;
			class49.Text = null;
			class51.AcceptRightClick = true;
			class51.Bounds = new global::System.Drawing.Rectangle(372, 32, 46, 26);
			class51.ButtonType = global::ns21.Enum32.const_1;
			class51.Enabled = true;
			class51.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton29.Icon");
			class51.Name = "Railroad";
			class52.Damage = 195;
			class52.NormalQuantity = 0;
			class52.OrganicQuantity = 0;
			class51.Overlay = class52;
			class51.Selected = false;
			class51.Text = null;
			class53.AcceptRightClick = true;
			class53.Bounds = new global::System.Drawing.Rectangle(72, 62, 46, 26);
			class53.ButtonType = global::ns21.Enum32.const_2;
			class53.Enabled = true;
			class53.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton30.Icon");
			class53.Name = "1$ Bill";
			class53.Overlay = overlay;
			class53.Selected = false;
			class53.Text = null;
			class54.AcceptRightClick = true;
			class54.Bounds = new global::System.Drawing.Rectangle(122, 62, 46, 26);
			class54.ButtonType = global::ns21.Enum32.const_2;
			class54.Enabled = true;
			class54.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton31.Icon");
			class54.Name = "Small Magnet";
			class54.Overlay = overlay2;
			class54.Selected = false;
			class54.Text = null;
			class55.AcceptRightClick = true;
			class55.Bounds = new global::System.Drawing.Rectangle(172, 62, 46, 26);
			class55.ButtonType = global::ns21.Enum32.const_2;
			class55.Enabled = true;
			class55.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton32.Icon");
			class55.Name = "5$ Bill";
			class55.Overlay = overlay3;
			class55.Selected = false;
			class55.Text = null;
			class56.AcceptRightClick = true;
			class56.Bounds = new global::System.Drawing.Rectangle(222, 62, 46, 26);
			class56.ButtonType = global::ns21.Enum32.const_2;
			class56.Enabled = true;
			class56.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton33.Icon");
			class56.Name = "Big Magnet";
			class56.Overlay = overlay4;
			class56.Selected = false;
			class56.Text = null;
			class57.AcceptRightClick = true;
			class57.Bounds = new global::System.Drawing.Rectangle(272, 62, 46, 26);
			class57.ButtonType = global::ns21.Enum32.const_2;
			class57.Enabled = true;
			class57.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton34.Icon");
			class57.Name = "10$ Bill";
			class57.Overlay = overlay5;
			class57.Selected = false;
			class57.Text = null;
			class58.AcceptRightClick = true;
			class58.Bounds = new global::System.Drawing.Rectangle(322, 62, 46, 26);
			class58.ButtonType = global::ns21.Enum32.const_2;
			class58.Enabled = true;
			class58.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton35.Icon");
			class58.Name = "Hypno-Goggles";
			class58.Overlay = overlay6;
			class58.Selected = false;
			class58.Text = null;
			class59.AcceptRightClick = true;
			class59.Bounds = new global::System.Drawing.Rectangle(372, 62, 46, 26);
			class59.ButtonType = global::ns21.Enum32.const_2;
			class59.Enabled = true;
			class59.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton36.Icon");
			class59.Name = "Presentation";
			class59.Overlay = overlay7;
			class59.Selected = false;
			class59.Text = null;
			class60.AcceptRightClick = true;
			class60.Bounds = new global::System.Drawing.Rectangle(72, 92, 46, 26);
			class60.ButtonType = global::ns21.Enum32.const_3;
			class60.Enabled = true;
			class60.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton37.Icon");
			class60.Name = "Bike Horn";
			class61.Damage = 4;
			class61.NormalQuantity = 0;
			class61.OrganicQuantity = 0;
			class60.Overlay = class61;
			class60.Selected = false;
			class60.Text = null;
			class62.AcceptRightClick = true;
			class62.Bounds = new global::System.Drawing.Rectangle(122, 92, 46, 26);
			class62.ButtonType = global::ns21.Enum32.const_3;
			class62.Enabled = true;
			class62.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton38.Icon");
			class62.Name = "Whistle";
			class63.Damage = 7;
			class63.NormalQuantity = 0;
			class63.OrganicQuantity = 0;
			class62.Overlay = class63;
			class62.Selected = false;
			class62.Text = null;
			class64.AcceptRightClick = true;
			class64.Bounds = new global::System.Drawing.Rectangle(172, 92, 46, 26);
			class64.ButtonType = global::ns21.Enum32.const_3;
			class64.Enabled = true;
			class64.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton39.Icon");
			class64.Name = "Bugle";
			class65.Damage = 11;
			class65.NormalQuantity = 0;
			class65.OrganicQuantity = 0;
			class64.Overlay = class65;
			class64.Selected = false;
			class64.Text = null;
			class66.AcceptRightClick = true;
			class66.Bounds = new global::System.Drawing.Rectangle(222, 92, 46, 26);
			class66.ButtonType = global::ns21.Enum32.const_3;
			class66.Enabled = true;
			class66.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton40.Icon");
			class66.Name = "Aoogah";
			class67.Damage = 16;
			class67.NormalQuantity = 0;
			class67.OrganicQuantity = 0;
			class66.Overlay = class67;
			class66.Selected = false;
			class66.Text = null;
			class68.AcceptRightClick = true;
			class68.Bounds = new global::System.Drawing.Rectangle(272, 92, 46, 26);
			class68.ButtonType = global::ns21.Enum32.const_3;
			class68.Enabled = true;
			class68.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton41.Icon");
			class68.Name = "Elephant Trunk";
			class69.Damage = 21;
			class69.NormalQuantity = 0;
			class69.OrganicQuantity = 0;
			class68.Overlay = class69;
			class68.Selected = false;
			class68.Text = null;
			class70.AcceptRightClick = true;
			class70.Bounds = new global::System.Drawing.Rectangle(322, 92, 46, 26);
			class70.ButtonType = global::ns21.Enum32.const_3;
			class70.Enabled = true;
			class70.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton42.Icon");
			class70.Name = "Foghorn";
			class71.Damage = 50;
			class71.NormalQuantity = 0;
			class71.OrganicQuantity = 0;
			class70.Overlay = class71;
			class70.Selected = false;
			class70.Text = null;
			class72.AcceptRightClick = true;
			class72.Bounds = new global::System.Drawing.Rectangle(372, 92, 46, 26);
			class72.ButtonType = global::ns21.Enum32.const_3;
			class72.Enabled = true;
			class72.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton43.Icon");
			class72.Name = "Opera Singer";
			class73.Damage = 90;
			class73.NormalQuantity = 0;
			class73.OrganicQuantity = 0;
			class72.Overlay = class73;
			class72.Selected = false;
			class72.Text = null;
			class74.AcceptRightClick = true;
			class74.Bounds = new global::System.Drawing.Rectangle(72, 122, 46, 26);
			class74.ButtonType = global::ns21.Enum32.const_4;
			class74.Enabled = true;
			class74.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton44.Icon");
			class74.Name = "Cupcake";
			class75.Damage = 6;
			class75.NormalQuantity = 0;
			class75.OrganicQuantity = 0;
			class74.Overlay = class75;
			class74.Selected = false;
			class74.Text = null;
			class76.AcceptRightClick = true;
			class76.Bounds = new global::System.Drawing.Rectangle(122, 122, 46, 26);
			class76.ButtonType = global::ns21.Enum32.const_4;
			class76.Enabled = true;
			class76.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton45.Icon");
			class76.Name = "Fruit Pie Slice";
			class77.Damage = 10;
			class77.NormalQuantity = 0;
			class77.OrganicQuantity = 0;
			class76.Overlay = class77;
			class76.Selected = false;
			class76.Text = null;
			class78.AcceptRightClick = true;
			class78.Bounds = new global::System.Drawing.Rectangle(172, 122, 46, 26);
			class78.ButtonType = global::ns21.Enum32.const_4;
			class78.Enabled = true;
			class78.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton46.Icon");
			class78.Name = "Cream Pie Slice";
			class79.Damage = 17;
			class79.NormalQuantity = 0;
			class79.OrganicQuantity = 0;
			class78.Overlay = class79;
			class78.Selected = false;
			class78.Text = null;
			class80.AcceptRightClick = true;
			class80.Bounds = new global::System.Drawing.Rectangle(222, 122, 46, 26);
			class80.ButtonType = global::ns21.Enum32.const_4;
			class80.Enabled = true;
			class80.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton47.Icon");
			class80.Name = "Whole Fruit Pie";
			class81.Damage = 27;
			class81.NormalQuantity = 0;
			class81.OrganicQuantity = 0;
			class80.Overlay = class81;
			class80.Selected = false;
			class80.Text = null;
			class82.AcceptRightClick = true;
			class82.Bounds = new global::System.Drawing.Rectangle(272, 122, 46, 26);
			class82.ButtonType = global::ns21.Enum32.const_4;
			class82.Enabled = true;
			class82.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton48.Icon");
			class82.Name = "Whole Cream Pie";
			class83.Damage = 40;
			class83.NormalQuantity = 0;
			class83.OrganicQuantity = 0;
			class82.Overlay = class83;
			class82.Selected = false;
			class82.Text = null;
			class84.AcceptRightClick = true;
			class84.Bounds = new global::System.Drawing.Rectangle(322, 122, 46, 26);
			class84.ButtonType = global::ns21.Enum32.const_4;
			class84.Enabled = true;
			class84.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton49.Icon");
			class84.Name = "Birthday Cake";
			class85.Damage = 100;
			class85.NormalQuantity = 0;
			class85.OrganicQuantity = 0;
			class84.Overlay = class85;
			class84.Selected = false;
			class84.Text = null;
			class86.AcceptRightClick = true;
			class86.Bounds = new global::System.Drawing.Rectangle(372, 122, 46, 26);
			class86.ButtonType = global::ns21.Enum32.const_4;
			class86.Enabled = true;
			class86.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton50.Icon");
			class86.Name = "Wedding Cake";
			class87.Damage = 120;
			class87.NormalQuantity = 0;
			class87.OrganicQuantity = 0;
			class86.Overlay = class87;
			class86.Selected = false;
			class86.Text = null;
			class88.AcceptRightClick = true;
			class88.Bounds = new global::System.Drawing.Rectangle(72, 152, 46, 26);
			class88.ButtonType = global::ns21.Enum32.const_5;
			class88.Enabled = true;
			class88.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton51.Icon");
			class88.Name = "Squirting Flower";
			class89.Damage = 4;
			class89.NormalQuantity = 0;
			class89.OrganicQuantity = 0;
			class88.Overlay = class89;
			class88.Selected = false;
			class88.Text = null;
			class90.AcceptRightClick = true;
			class90.Bounds = new global::System.Drawing.Rectangle(122, 152, 46, 26);
			class90.ButtonType = global::ns21.Enum32.const_5;
			class90.Enabled = true;
			class90.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton52.Icon");
			class90.Name = "Glass of Water";
			class91.Damage = 8;
			class91.NormalQuantity = 0;
			class91.OrganicQuantity = 0;
			class90.Overlay = class91;
			class90.Selected = false;
			class90.Text = null;
			class92.AcceptRightClick = true;
			class92.Bounds = new global::System.Drawing.Rectangle(172, 152, 46, 26);
			class92.ButtonType = global::ns21.Enum32.const_5;
			class92.Enabled = true;
			class92.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton53.Icon");
			class92.Name = "Squirt Gun";
			class93.Damage = 12;
			class93.NormalQuantity = 0;
			class93.OrganicQuantity = 0;
			class92.Overlay = class93;
			class92.Selected = false;
			class92.Text = null;
			class94.AcceptRightClick = true;
			class94.Bounds = new global::System.Drawing.Rectangle(222, 152, 46, 26);
			class94.ButtonType = global::ns21.Enum32.const_5;
			class94.Enabled = true;
			class94.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton54.Icon");
			class94.Name = "Seltzer Bottle";
			class95.Damage = 21;
			class95.NormalQuantity = 0;
			class95.OrganicQuantity = 0;
			class94.Overlay = class95;
			class94.Selected = false;
			class94.Text = null;
			class96.AcceptRightClick = true;
			class96.Bounds = new global::System.Drawing.Rectangle(272, 152, 46, 26);
			class96.ButtonType = global::ns21.Enum32.const_5;
			class96.Enabled = true;
			class96.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton55.Icon");
			class96.Name = "Fire Hose";
			class97.Damage = 30;
			class97.NormalQuantity = 0;
			class97.OrganicQuantity = 0;
			class96.Overlay = class97;
			class96.Selected = false;
			class96.Text = null;
			class98.AcceptRightClick = true;
			class98.Bounds = new global::System.Drawing.Rectangle(322, 152, 46, 26);
			class98.ButtonType = global::ns21.Enum32.const_5;
			class98.Enabled = true;
			class98.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton56.Icon");
			class98.Name = "Storm Cloud";
			class99.Damage = 80;
			class99.NormalQuantity = 0;
			class99.OrganicQuantity = 0;
			class98.Overlay = class99;
			class98.Selected = false;
			class98.Text = null;
			class100.AcceptRightClick = true;
			class100.Bounds = new global::System.Drawing.Rectangle(372, 152, 46, 26);
			class100.ButtonType = global::ns21.Enum32.const_5;
			class100.Enabled = true;
			class100.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton57.Icon");
			class100.Name = "Geyser";
			class101.Damage = 105;
			class101.NormalQuantity = 0;
			class101.OrganicQuantity = 0;
			class100.Overlay = class101;
			class100.Selected = false;
			class100.Text = null;
			class102.AcceptRightClick = true;
			class102.Bounds = new global::System.Drawing.Rectangle(72, 182, 46, 26);
			class102.ButtonType = global::ns21.Enum32.const_6;
			class102.Enabled = true;
			class102.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton58.Icon");
			class102.Name = "Flower Pot";
			class103.Damage = 10;
			class103.NormalQuantity = 0;
			class103.OrganicQuantity = 0;
			class102.Overlay = class103;
			class102.Selected = false;
			class102.Text = null;
			class104.AcceptRightClick = true;
			class104.Bounds = new global::System.Drawing.Rectangle(122, 182, 46, 26);
			class104.ButtonType = global::ns21.Enum32.const_6;
			class104.Enabled = true;
			class104.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton59.Icon");
			class104.Name = "Sandbag";
			class105.Damage = 18;
			class105.NormalQuantity = 0;
			class105.OrganicQuantity = 0;
			class104.Overlay = class105;
			class104.Selected = false;
			class104.Text = null;
			class106.AcceptRightClick = true;
			class106.Bounds = new global::System.Drawing.Rectangle(172, 182, 46, 26);
			class106.ButtonType = global::ns21.Enum32.const_6;
			class106.Enabled = true;
			class106.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton60.Icon");
			class106.Name = "Anvil";
			class107.Damage = 30;
			class107.NormalQuantity = 0;
			class107.OrganicQuantity = 0;
			class106.Overlay = class107;
			class106.Selected = false;
			class106.Text = null;
			class108.AcceptRightClick = true;
			class108.Bounds = new global::System.Drawing.Rectangle(222, 182, 46, 26);
			class108.ButtonType = global::ns21.Enum32.const_6;
			class108.Enabled = true;
			class108.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton61.Icon");
			class108.Name = "Big Weight";
			class109.Damage = 45;
			class109.NormalQuantity = 0;
			class109.OrganicQuantity = 0;
			class108.Overlay = class109;
			class108.Selected = false;
			class108.Text = null;
			class110.AcceptRightClick = true;
			class110.Bounds = new global::System.Drawing.Rectangle(272, 182, 46, 26);
			class110.ButtonType = global::ns21.Enum32.const_6;
			class110.Enabled = true;
			class110.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton62.Icon");
			class110.Name = "Safe";
			class111.Damage = 60;
			class111.NormalQuantity = 0;
			class111.OrganicQuantity = 0;
			class110.Overlay = class111;
			class110.Selected = false;
			class110.Text = null;
			class112.AcceptRightClick = true;
			class112.Bounds = new global::System.Drawing.Rectangle(322, 182, 46, 26);
			class112.ButtonType = global::ns21.Enum32.const_6;
			class112.Enabled = true;
			class112.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton63.Icon");
			class112.Name = "Grand Piano";
			class113.Damage = 170;
			class113.NormalQuantity = 0;
			class113.OrganicQuantity = 0;
			class112.Overlay = class113;
			class112.Selected = false;
			class112.Text = null;
			class114.AcceptRightClick = true;
			class114.Bounds = new global::System.Drawing.Rectangle(372, 182, 46, 26);
			class114.ButtonType = global::ns21.Enum32.const_6;
			class114.Enabled = true;
			class114.Icon = (global::System.Drawing.Image)componentResourceManager.GetObject("buttonBoardButton64.Icon");
			class114.Name = "Toontanic";
			class115.Damage = 180;
			class115.NormalQuantity = 0;
			class115.OrganicQuantity = 0;
			class114.Overlay = class115;
			class114.Selected = false;
			class114.Text = null;
			this.GagBoard.Buttons.Add(class31);
			this.GagBoard.Buttons.Add(class32);
			this.GagBoard.Buttons.Add(class33);
			this.GagBoard.Buttons.Add(class34);
			this.GagBoard.Buttons.Add(class36);
			this.GagBoard.Buttons.Add(class37);
			this.GagBoard.Buttons.Add(class38);
			this.GagBoard.Buttons.Add(class39);
			this.GagBoard.Buttons.Add(class41);
			this.GagBoard.Buttons.Add(class43);
			this.GagBoard.Buttons.Add(class45);
			this.GagBoard.Buttons.Add(class47);
			this.GagBoard.Buttons.Add(class49);
			this.GagBoard.Buttons.Add(class51);
			this.GagBoard.Buttons.Add(class53);
			this.GagBoard.Buttons.Add(class54);
			this.GagBoard.Buttons.Add(class55);
			this.GagBoard.Buttons.Add(class56);
			this.GagBoard.Buttons.Add(class57);
			this.GagBoard.Buttons.Add(class58);
			this.GagBoard.Buttons.Add(class59);
			this.GagBoard.Buttons.Add(class60);
			this.GagBoard.Buttons.Add(class62);
			this.GagBoard.Buttons.Add(class64);
			this.GagBoard.Buttons.Add(class66);
			this.GagBoard.Buttons.Add(class68);
			this.GagBoard.Buttons.Add(class70);
			this.GagBoard.Buttons.Add(class72);
			this.GagBoard.Buttons.Add(class74);
			this.GagBoard.Buttons.Add(class76);
			this.GagBoard.Buttons.Add(class78);
			this.GagBoard.Buttons.Add(class80);
			this.GagBoard.Buttons.Add(class82);
			this.GagBoard.Buttons.Add(class84);
			this.GagBoard.Buttons.Add(class86);
			this.GagBoard.Buttons.Add(class88);
			this.GagBoard.Buttons.Add(class90);
			this.GagBoard.Buttons.Add(class92);
			this.GagBoard.Buttons.Add(class94);
			this.GagBoard.Buttons.Add(class96);
			this.GagBoard.Buttons.Add(class98);
			this.GagBoard.Buttons.Add(class100);
			this.GagBoard.Buttons.Add(class102);
			this.GagBoard.Buttons.Add(class104);
			this.GagBoard.Buttons.Add(class106);
			this.GagBoard.Buttons.Add(class108);
			this.GagBoard.Buttons.Add(class110);
			this.GagBoard.Buttons.Add(class112);
			this.GagBoard.Buttons.Add(class114);
			this.GagBoard.DisabledEndColor = global::System.Drawing.Color.FromArgb(37, 37, 37);
			this.GagBoard.DisabledStartColor = global::System.Drawing.Color.FromArgb(163, 163, 163);
			this.GagBoard.DownEndColor = global::System.Drawing.Color.FromArgb(111, 2, 14);
			this.GagBoard.DownStartColor = global::System.Drawing.Color.FromArgb(250, 102, 102);
			this.GagBoard.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GagBoard.ForeColor = global::System.Drawing.Color.SkyBlue;
			this.GagBoard.HoverEndColor = global::System.Drawing.Color.FromArgb(157, 0, 18);
			this.GagBoard.HoverRadialCenterColor = global::System.Drawing.Color.FromArgb(200, 255, 0, 0);
			this.GagBoard.HoverRadialSurroundColor = global::System.Drawing.Color.FromArgb(0, 255, 0, 0);
			this.GagBoard.HoverStartColor = global::System.Drawing.Color.FromArgb(248, 152, 152);
			this.GagBoard.Location = new global::System.Drawing.Point(118, 126);
			this.GagBoard.Margin = new global::System.Windows.Forms.Padding(0);
			this.GagBoard.Name = "GagBoard";
			this.GagBoard.NormalEndColor = global::System.Drawing.Color.FromArgb(1, 137, 224);
			this.GagBoard.NormalStartColor = global::System.Drawing.Color.FromArgb(76, 181, 248);
			this.GagBoard.SelectedEndColor = global::System.Drawing.Color.FromArgb(0, 157, 0);
			this.GagBoard.SelectedRadialCenterColor = global::System.Drawing.Color.FromArgb(200, 0, 255, 0);
			this.GagBoard.SelectedRadialSurroundColor = global::System.Drawing.Color.FromArgb(0, 0, 255, 0);
			this.GagBoard.SelectedStartColor = global::System.Drawing.Color.FromArgb(152, 248, 165);
			this.GagBoard.Size = new global::System.Drawing.Size(426, 210);
			this.GagBoard.TabIndex = 0;
			this.GagBoard.Text = "buttonBoard1";
			this.GagBoard.TextFont = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GagBoard.ToolTipsEnabled = true;
			this.GagBoard.ButtonClicked += new global::System.EventHandler<global::ns17.EventArgs21>(this.method_3);
			this.HowToOpenHelpLabel.AutoSize = true;
			this.HowToOpenHelpLabel.BackColor = global::System.Drawing.Color.Transparent;
			this.HowToOpenHelpLabel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.HowToOpenHelpLabel.Location = new global::System.Drawing.Point(0, 486);
			this.HowToOpenHelpLabel.Name = "HowToOpenHelpLabel";
			this.HowToOpenHelpLabel.Size = new global::System.Drawing.Size(105, 12);
			this.HowToOpenHelpLabel.TabIndex = 21;
			this.HowToOpenHelpLabel.Text = "Press F1 to display help.";
			base.AllowFormDrag = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("$this.BackgroundImage");
			base.ClientSize = new global::System.Drawing.Size(700, 500);
			base.Controls.Add(this.HowToOpenHelpLabel);
			base.Controls.Add(this.MaxMessage);
			base.Controls.Add(this.ShowToolTips);
			base.Controls.Add(this.KeepOnTop);
			base.Controls.Add(this.Lured);
			base.Controls.Add(this.HitPoints);
			base.Controls.Add(this.MaxCog);
			base.Controls.Add(this.MaxCogTitle);
			base.Controls.Add(this.ClearButtonPanel);
			base.Controls.Add(this.label15);
			base.Controls.Add(this.SosBoard);
			base.Controls.Add(this.label14);
			base.Controls.Add(this.label12);
			base.Controls.Add(this.label10);
			base.Controls.Add(this.label8);
			base.Controls.Add(this.label6);
			base.Controls.Add(this.label13);
			base.Controls.Add(this.label11);
			base.Controls.Add(this.label9);
			base.Controls.Add(this.label4);
			base.Controls.Add(this.label7);
			base.Controls.Add(this.label5);
			base.Controls.Add(this.label3);
			base.Controls.Add(this.label2);
			base.Controls.Add(this.ToonUpTitle);
			base.Controls.Add(this.GagBoard);
			this.DoubleBuffered = true;
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.MaximizeBox = false;
			base.Name = "GagAMatic";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "The ToonTown Spoofer : The Gag-A-Matic";
			base.HelpRequested += new global::System.Windows.Forms.HelpEventHandler(this.GagAMatic_HelpRequested);
			this.ClearButtonPanel.ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040002C6 RID: 710
		private global::System.ComponentModel.IContainer icontainer_0;

		// Token: 0x040002C7 RID: 711
		private global::ns24.Control4 GagBoard;

		// Token: 0x040002C8 RID: 712
		private global::System.Windows.Forms.CheckBox Lured;

		// Token: 0x040002C9 RID: 713
		private global::System.Windows.Forms.Label ToonUpTitle;

		// Token: 0x040002CA RID: 714
		private global::System.Windows.Forms.Label label2;

		// Token: 0x040002CB RID: 715
		private global::System.Windows.Forms.Label label3;

		// Token: 0x040002CC RID: 716
		private global::System.Windows.Forms.Label label4;

		// Token: 0x040002CD RID: 717
		private global::System.Windows.Forms.Label label5;

		// Token: 0x040002CE RID: 718
		private global::System.Windows.Forms.Label label6;

		// Token: 0x040002CF RID: 719
		private global::System.Windows.Forms.Label label7;

		// Token: 0x040002D0 RID: 720
		private global::System.Windows.Forms.Label label8;

		// Token: 0x040002D1 RID: 721
		private global::System.Windows.Forms.Label label9;

		// Token: 0x040002D2 RID: 722
		private global::System.Windows.Forms.Label label10;

		// Token: 0x040002D3 RID: 723
		private global::System.Windows.Forms.Label label11;

		// Token: 0x040002D4 RID: 724
		private global::System.Windows.Forms.Label label12;

		// Token: 0x040002D5 RID: 725
		private global::System.Windows.Forms.Label label13;

		// Token: 0x040002D6 RID: 726
		private global::System.Windows.Forms.Label label14;

		// Token: 0x040002D7 RID: 727
		private global::ns24.Control4 SosBoard;

		// Token: 0x040002D8 RID: 728
		private global::System.Windows.Forms.Button btnClear;

		// Token: 0x040002D9 RID: 729
		private global::System.Windows.Forms.Label label15;

		// Token: 0x040002DA RID: 730
		private global::System.Windows.Forms.Panel ClearButtonPanel;

		// Token: 0x040002DB RID: 731
		private global::System.Windows.Forms.Label MaxCogTitle;

		// Token: 0x040002DC RID: 732
		private global::System.Windows.Forms.Label MaxCog;

		// Token: 0x040002DD RID: 733
		private global::System.Windows.Forms.Label HitPoints;

		// Token: 0x040002DE RID: 734
		private global::System.Windows.Forms.CheckBox KeepOnTop;

		// Token: 0x040002DF RID: 735
		private global::ns15.TextFader MaxMessage;

		// Token: 0x040002E0 RID: 736
		private global::System.Windows.Forms.CheckBox ShowToolTips;

		// Token: 0x040002E1 RID: 737
		private global::System.Windows.Forms.ToolTip toolTip_0;

		// Token: 0x040002E2 RID: 738
		private global::System.Windows.Forms.Label HowToOpenHelpLabel;
	}
}
